name: 'Insight CMP'

trigger: 
- '*'

# User defined parameters 
variables:
  - group: pipeline_variables
  - name: UserName
    value: "ado"
  - name: UserEmail
    value: "pipeline@ado.com"
  - name: OriginRepo
    value: "https://dev.azure.com/nsitmspdevops/Insight%20CMP%20Azure%20IaC/_git/test"
  - name: TargetRepo
    value: "https://dev.azure.com/TEK009/Sample%20Project/_git/Sample%20Project"

stages:
  - stage: 'cloningDevelopmentRepo'
    pool:
        vmImage: 'ubuntu-latest'
    jobs:
    - job: CloningCentralRepo
      displayName: 'Cloning AWS_Onboard'
    - deployment: 'UpdatingCentralRepo'
      displayName: "Updating AWS_Onboard"
      environment: Central
      strategy:
        runOnce:
          deploy:
            steps:
              - bash: |
                  git config --global user.name $(UserName)
                  git config --global user.email $(UserEmail)
                  git config --global credential.authority basic
                  git config --global http.sslVerify "false"
                  # the personal account token is defined as pipeline variable encrypted
                  B64_PAT=$(printf "%s"":$(PAT_REMOTE)" | base64)
                  echo ${B64_PAT}
                  git -c http.extraHeader="Authorization: Basic ${B64_PAT}" clone --bare $(OriginRepo)
                  git config -l
                  echo "git clone done"
                  cd test.git
                  B64_PAT=$(printf "%s"":$(PAT_LOCAL)" | base64)
                  git -c http.extraHeader="Authorization: Basic ${B64_PAT}" push --mirror $(TargetRepo)
                  echo "git mirror done"
                  cd ..
                  rm -rf test.git
                displayName: 'Mirror the repo from the Origin project to the Target project'
